name: team_management_software
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  sizer: ^2.0.13
  http: ^0.13.3
  flutter_local_notifications: ^8.0.0
  firebase_messaging: ^10.0.2
  firebase_core: ^1.3.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  firebase_storage: ^10.0.1
  file_picker: ^3.0.3
  flutter_pdfview: ^1.1.0
  path_provider: ^2.0.2
  flutter_secure_storage: ^4.2.0
  firebase_auth: ^3.0.1
  chewie:
  firebase_analytics: ^7.0.1
  focused_menu: ^1.0.5
  flutter_sound_lite: ^8.1.9
  permission_handler: ^8.1.4+2
  loading_indicator: ^3.0.1
  flutter_slidable: ^0.6.0
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - images/

